### ISSUE TITLE
https://wallet.lum.network/ returns TX hash w/ lowercase letters

### ISSUE THREAD

**Issue by HathorNodes** [lum-network/mainnet#29]
If you complete a transaction using the lum wallet the resulting tx hash has lowercase letters:

![Screen Shot 2022-01-13 at 3 03 07 PM](https://user-images.githubusercontent.com/84766250/149401078-5d072da6-ac43-4b91-ba1c-2b9723ede3d2.png)

Searching the explorer for the tx like this doesn't find a result:

https://explorer.lum.network/search/ccb59630a4311eae6ae8e656ff65d398fa8d2fd2b692b670c2b0510a0b89c75c

I can go to Mintscan and find that tx:

https://www.mintscan.io/lum/txs/ccb59630a4311eae6ae8e656ff65d398fa8d2fd2b692b670c2b0510a0b89c75c

If I take their capitalized version of the tx and search the explorer again, I can find the tx:

https://explorer.lum.network/txs/CCB59630A4311EAE6AE8E656FF65D398FA8D2FD2B692B670C2B0510A0B89C75C

**Comment by lebascou** [comment]
Thanks for the feedback, team has been notified, closing the issue since it is not in the appropriate repository
