### ISSUE TITLE
No way to create proposals

### ISSUE THREAD

**Issue by blockchainenthusiast** [lum-network/mainnet#31]
Hi I was searching for documentation on how to create a proposal but didn't find any or see any way to accomplish it from the UI. Has this feature been enabled if not are there plans to do so?

**Comment by Segfaultd** [comment]
Hello @blockchainenthusiast, and sorry for late reply, didn't notice.

In order to create a proposal, you have to use the chain CLI. At the moment, we don't provide that feature in the web UI.

Regards,
